story1/urls.py
from . import views
from django.urls import path

app_name='story1'

urlpatterns = [
	path('', views.story1page, name='story1page')
]

story3/urls.py
from . import views
from django.urls import path

app_name='story3'

urlpatterns = [
	path('', views.story3page, name='story3page'),
	path('gallery/', views.gallery, name='gallery'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
]

story5/urls.py
from . import views
from django.urls import path

app_name = 'story5'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('add_course', views.add_course, name='add_course'),
    path('delete_course/<int:id>', views.delete_course, name='delete_course'),
    path('course_detail/<int:id>', views.course_detail, name='course_detail'),
]

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

class Courses(models.Model):
	name = models.CharField(max_length=100)
	lecturer = models.CharField(max_length=100)
	sks = models.IntegerField()
	description = models.TextField()
	period = models.CharField(max_length=100)
	classroom = models.CharField(max_length=100)

	def __str__(self):
		return "{} - {} - {} - {} - {} - {}".format(self.name, self.lecturer, self.sks, self.description, self.period, self.classroom)

story5/forms.py
from django import forms
from django.forms import ModelForm 
from . import models

class CreateCoursesForm(forms.ModelForm):
	class Meta:
		model = models.Courses
		fields = [
			"name",
			"lecturer",
			"sks",
			"description",
			"period",
			"classroom",
		]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.Meta.fields:
			self.fields[field].widget.attrs.update({
				'class': 'form-control',
			})

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1page(request):
	response = {
		'title': 'Story 1'
	}
	return render(request, 'story1.html', response)

story3/views.py
from django.shortcuts import render

# Create your views here.
def story3page(request):
	response = {
		'title': 'Story 3'
	}
	return render(request, 'story3.html', response)

def gallery(request):
	response = {
		'title': 'Gallery'
	}
	return render(request, 'gallery.html', response)

story5/views.py
from django.shortcuts import render, redirect
from .models import Courses
from . import forms
# Create your views here.

def courses(request):
	courses = Courses.objects.all()
	response = {
		'courses' : courses
	}
	return render(request, 'courses.html', response)

def add_course(request):
    response = {
        'course_form': forms.CreateCoursesForm()
    }

    if request.method == "POST":
    	course_form = forms.CreateCoursesForm(request.POST)
    	if course_form.is_valid():
    		instance = course_form.save(commit=False)
    		instance.save()
    		return redirect('story5:courses')
    return render(request, 'add_course.html', response)

def delete_course(request, id):
	course = Courses.objects.get(id=id)
	course.delete()
	return redirect('story5:courses')

def course_detail(request, id):
    course = Courses.objects.get(id=id)
    response = {
        'course_content': course
    }
    return render(request, 'course_detail.html', response)

story1/templates/story1.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory1.css' %}">
{% endblock %}

{% block content %}
<div class="background">
    <h1>My Biodata</h1>
    <div class="wrap-column">
        <div class="wrap-row">
            <img src="{% static 'css/yola.jpg' %}" alt="yola" style="width:300px;height:450px;">

            <div class="biodata">
                <p>Nama &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; Yolanda Emanuella Sutanto</p>
                <p>NPM &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; 1906299206</p>
                <p>Angkatan &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;:&nbsp; &nbsp;Maung 2019</p>
                <p>Tempat Kuliah &nbsp;: &nbsp; Universitas Indonesia</p>
                <p>Hobi &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : &nbsp; Bermain piano, mendengarkan musik, &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bermain badminton, bermain biola,<br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;menonton drama.</p>
                <p><strong>- Deskripsi - </strong><br>Nama panggilan saya adalah Yola. Saya lahir di Cirebon pada tanggal 24 September 2001.
                Saya memiliki golongan darah O, begitupun juga dengan anggota keluarga saya. Warna kesukaan
                saya adalah ungu dan biru. Saya memiliki sifat yang cukup pendiam dan kurang percaya diri,
                namun saya merupakan orang yang teliti.</p>
            </div>

            <div class="wrap-column">
                <div class="tabel">
                    <table style="width:100%" border=1>
                        <p><strong>Riwayat Pendidikan: </strong></p>
                        <tr>
                            <td>Universitas Indonesia</td>
                            <td>2019 - saat ini</td>
                        </tr>
        
                        <tr>
                            <td>SMA Santa Maria 1 Cirebon</td>
                            <td>2016 - 2019</td>
                        </tr>
                        <tr>
        
                            <td>SMP Santa Maria Cirebon</td>
                            <td>2013 - 2016</td>
                        </tr>
        
                        <tr>
                            <td>SDK BPK Penabur Cirebon</td>
                            <td>2007 - 2013</td>
                        </tr>
        
                        <tr>
                            <td>TK Permata Bunda Cirebon</td>
                            <td>2005 - 2007</td>
                        </tr>
                    </table>
                </div>

                <div class="socmed">
                    <br><p style="font-family:Solway;font-size:18px"><strong>Social Media:</strong></p>
                    <div class="wrap-column">
                        <div class="wrap-row-socmed">
                            <img src="{% static 'css/instagram.png' %}" alt="instagram" style="width:60px; height:60px; margin:0.5rem;">
                            <p style="font-family:Solway;font-size:17px">yolandaesutanto</p>
                        </div>

                        <div class="wrap-row-socmed">
                            <img src="{% static 'css/line.png' %}" alt="line" style="width:60px; height:60px; margin:0.5rem;">
                            <p style="font-family:Solway;font-size:17px">yolandaesutanto</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

story3/templates/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
{% endblock %}

{% block content %}

<div class="gallery">
  <br/>
  <div class="gallery-title">
    Gallery
  </div>
  <br/>
  <div class="centered2">
    The most in this gallery are my piano duet play videos. <br/>
    Hope you enjoy :)
  </div>
  <br/>
  <br/>

  <div class="wrap-flex">
    <div class="margin-gallery">
      <iframe width="350" height="300" src="https://www.youtube.com/embed/jURXIMBvUII" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <br />
      Flood Time - Eric Thiman
    </div>

    <div class="margin-gallery">
      <video width="350" height="300" controls>
        <source src="{% static 'css/oholynightt.mp4' %}" type="video/mp4" />
      </video>
      <br />
      O Holy Night - Adolphe Adam
    </div>

    <div class="margin-gallery">
      <video width="350" height="300" controls>
        <source src="{% static 'css/riverflowsinyouu.mp4' %}" type="video/mp4" />
      </video>
      <br />
      River Flows in You - Yiruma
    </div>

    <div class="margin-gallery">
      <video width="350" height="300" controls>
        <source src="{% static 'css/allegretto-in-f.mp4' %}" type="video/mp4" />
      </video>
      <br />
      Allegretto in F - J.C.F Bach <br/> (4 hands cover) 
    </div>

    <div class="margin-gallery">
      <video width="350" height="300" controls>
        <source src="{% static 'css/beautyandthebeast.mp4' %}" type="video/mp4" />
      </video>
      <br />
      Beauty and The Beast <br/> from "Beauty and The Beast" [1/3]
    </div>

    <div class="margin-gallery">
      <video width="350" height="300" controls>
        <source src="{% static 'css/part2.mp4' %}" type="video/mp4" />
      </video>
      <br />
      Beauty and The Beast <br/> from "Beauty and The Beast" [2/3]
    </div>

    <div class="margin-gallery">
      <video width="350" height="300" controls>
        <source src="{% static 'css/part3.mp4' %}" type="video/mp4" />
      </video>
      <br />
      Beauty and The Beast <br/> from "Beauty and The Beast" [3/3]
    </div>
  </div>

  <div class="button-center-gallery">
    <div class="spacing">
      <button><a href="{% url 'story3:story3page' %}">Back to home</a></button>
    </div>
  </div>
</div>
{% endblock %}

story3/templates/story3.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/stylestory3.css' %}">
{% endblock %}

{% block content %}
<div class="background" id="home">
    <div class="centered">
        <div class="title">
            Welcome!
            <br/>
            How can I help you?
            <br/>
        </div>    
        <div class="wrap-row">
            <div class="spacing">
              <button>
                <a href="#aboutme">I want to explore more...</a>
              </button>
            </div>
            <div class="spacing">
              <button><a href="#skills">I'm looking for hire...</a></button>
            </div>
        </div>
    </div>
</div>

<div class="page2" id="aboutme">
    <div class="wrapper">
        <div class="aboutme">
            <div style="display: flex; justify-content: center;">
                <img src="{% static 'css/aboutme.png' %}" alt="aboutme" style="width:210px;height:150px">
            </div> 
        </div>     
        <div class="wrap-row-aboutme">
            <div class="aboutleft">
                <img src="{% static 'css/yola-circle.png' %}" alt="yola" class="photo-yola" >
            </div>

            <div class="aboutright">
                <div class="paragraph">
                    Hello! My name is Yolanda Emanuella Sutanto. <br/> You can call me Yola. I’m currently studying at Faculty of Computer Science <br/> Universitas Indonesia majoring in Information Systems. <br/> 
                    I have 1 sister and 2 brothers. I love playing and listening to the music. <br/> I am a conscientious, patient, polite, and <br/> responsible person. 
                </div>

                <div class="paragraph-2">
                    Apart from that, I also have so many weakness, such as <br/> introvert, shy, and less-confident person. <br/> 
                    However, I will always try to do my best and fix all my weakness. <br/><br/> I hope we can make friends and work well!
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page3" id="skills">
    <div class="centered1">
        <div class="titlepage3">
            Skills
        </div>
    </div>

    <div class="wrap-row">
        <div class="margin-skills">
            <div class="hardskills">
                <div class="wrap-column">
                    <h1><strong>Hard skills:</strong></h1><br/>
                    <h2><strong>1. Computer</strong></h2>
                    - Programming Language <br/>
                    (Python and Java) <br/>
                    - Microsoft Office <br/>
                    - Typing and typing speed <br/>
                    - Online research <br/><br/>
                    <h2><strong>2. Language</strong></h2>
                    - Indonesian <br/>
                    - English <br/>
                </div>
            </div>
        </div>
        
        <div class="margin-skills">
            <div class="otherskills">
                <div class="wrap-column1">
                    <h1><strong>Other skills:</strong></h1><br/>
                    - Playing the piano <br/>
                    - Playing the violin <br/>
                    - Abacus <br/>
                    - Sight-reading <br/>
                    <div class="foto-skills">
                        <div style="display: flex; justify-content: center;">
                            <img src="{% static 'css/skills.png' %}" alt="skills" style="width:125px;height:125px">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="margin-skills">
            <div class="softskills">
                <div class="wrap-column2">
                    <h1><strong>Soft skills:</strong></h1><br/>
                    - Ethics / Integrity <br/>
                    - Critical thinking <br/>
                    - Commitment <br/>
                    - Motivation <br/>
                    - Team work <br/>
                    - Self management <br/>
                    - Flexible <br/>
                    - Time management <br/>
                </div>
            </div>
        </div>

        </div>
    </div>

</div>

<div class="page4" id="experience">
    <div class="centered1">
        <div class="titlepage4">
            My Experience
        </div>
    </div>

    <div class="experience">
        <h1><strong>Organizational + Project Experience:</strong></h1><br/>
        <strong>- Member Consulting SIG at SISTEM Fasilkom UI 2020</strong><br/>
        &nbsp; (On Going) Final Project in Collaboration with Kotakode <br/>
        <strong>- Avishai Ensemble (as Violinist)</strong><br/>
        &nbsp; Playing music for Sunday Service / the event in Cirebon and its surroundings <br/><br/>
        <h1><strong>Committee Experience:</strong></h1><br/>
        - Staff of Academic Division at PMB Fasilkom UI 2020 <br/>
        - Staff of Ticketing Division at Universitas Indonesia Goes to Cirebon 2020 <br/>
        - Staff of Public Relations and Publications Division at Social Project by New Fasilkom UI Students 2020
    </div>
</div>

<div class="page5" id="faq">
    <div class="centered1">
        <div class="titlepage5">
            FREQUENTLY ASKED QUESTIONS
        </div>
    </div>

    <section>
        <div class="container">
            <div class="accordion">
                <div class="accordion-item" id="question1">
                    <a class="accordion-link" href="#question1">
                        Can you tell me about your college?
                        <i class="icon ion-md-add"></i>
                        <i class="icon ion-md-remove"></i>
                    </a>
                    <div class="answer">
                        <p>
                            Now, I'm a 2nd year student at Universitas Indonesia, and a 3rd term student. Due to circumstances that are still not possible, the method of learning in this 3rd term is online through our homes. In this 3rd term, the courses
                            are getting more and more difficult, and there are also so many assignments that given. I feel very tired about
                            this 3rd term which has been running until now entering the week 3. But, I will do my best until the end of this semester.
                        </p>
                    </div>
                </div>

                <div class="accordion-item" id="question2">
                    <a class="accordion-link" href="#question2">
                        How old are you? And where are you from?
                        <i class="icon ion-md-add"></i>
                        <i class="icon ion-md-remove"></i>
                    </a>
                    <div class="answer">
                        <p>
                            I'm 19 years old, and I'm from Cirebon, a small city in West Java Province.
                        </p>
                    </div>
                </div>

                <div class="accordion-item" id="question3">
                    <a class="accordion-link" href="#question3">
                        What language do you use to create this website?
                        <i class="icon ion-md-add"></i>
                        <i class="icon ion-md-remove"></i>
                    </a>
                    <div class="answer">
                        <p>
                            I use HTML and CSS.
                        </p>
                    </div>
                </div>

                <div class="accordion-item" id="question4">
                    <a class="accordion-link" href="#question4">
                        What do you want to be after graduating from college?
                        <i class="icon ion-md-add"></i>
                        <i class="icon ion-md-remove"></i>
                    </a>
                    <div class="answer">
                        <p>
                            I want to be an IT Consultant, Project Manager, or Data Analyst. I hope my dreams will come true.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<div class="page6" id="contact">
    <div style="display: flex; justify-content: center;">
        <img src="{% static 'css/Contact-Me.png' %}" alt="contactme" style="width:400px; height:150px">
    </div>

    <div class="contact">
        <div class="wrap-column-contact">
            <div class="wrap-row">
                <div class="margin-contact">
                    <img src="{% static 'css/line.png' %}" alt="email" style="width:65px; height:65px">
                    &nbsp; &nbsp; <strong>yolandaesutanto</strong>
                </div>
            </div>

            <div class="wrap-row">
                <div class="margin-contact">
                    <img src="{% static 'css/instagram.png' %}" alt="instagram" style="width:60px; height:60px">
                    &nbsp; &nbsp; <strong>yolandaesutanto</strong>
                </div>
            </div>

            <div class="wrap-row">
                <div class="margin-contact">
                    <img src="{% static 'css/email.png' %}" alt="line" style="width:72px; height:75px">
                    &nbsp; &nbsp; <strong>yolandaemanuellas@gmail.com</strong>
                </div>
            </div>
        </div>
        
        <div class="button-center-gallery">
            <div class="spacing">
                <button><a href="#home">Back to home</a></button>
            </div>
        </div>

    </div>
</div>
{% endblock %}

story5/templates/add_course.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style_add_course.css' %}">
    <title>Add Course</title>
</head>
<body>
    <div class="course">
        <button><a href="{% url 'story5:courses' %}">See my courses!</a></button>
        <h1><b style="color:white">Add your courses!</b></h1>
        <div class="wrap">
            <form action="{% url 'story5:add_course' %}" method="POST">
                {% csrf_token %}
                {% for field in course_form.visible_fields %}
                <div class="form-group">
                    <div class="col-sm-6 offset-sm-3">
                        <h5>{{field.label_tag}} {{field}}</h5>
                    </div>
                </div>
                {% endfor %}
                <div style="text-align: center"><button type="submit">Add course</button></div>
            </form>
        </div>
    </div>
</body>
</html>

story5/templates/course_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style_course_detail.css' %}">
    <title>Course Detail</title>
</head>
<body>
    <div class="courses">
        <button><a href="{% url 'story5:courses' %}">Back to courses</a></button>

        <div class="centered">
            <div class="bordered">
                <h3><b>{{ course_content.name }}</b></h3>
                <h2>Dosen: {{ course_content.lecturer }}</h2>
                <h2>SKS: {{ course_content.sks }}</h2>
                <h2>Deskripsi Mata Kuliah: {{ course_content.description }}</h2>
                <h2>Tahun Ajaran: {{ course_content.period }}</h2>
                <h2>Ruang Kelas: {{ course_content.classroom }}</h2>
                <h2><b><a style="color: black" href="{% url 'story5:delete_course' id=course_content.id %}">Delete courses</a></b></h2>
            </div>
        </div>
    </div>
</body>
</html>

story5/templates/courses.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/stylestory5.css' %}">
    <title>Course</title>
</head>
<body>
    <div class="courses">
        <button><a href="{% url 'story5:add_course' %}">Add more courses!</a></button>
        <div class="wrap">
            {% if courses.count %}
            <h1>My Courses:</h1>
            {% for courses_content in courses %}

            <div class="bordered">
                <h3><b><a href="{% url 'story5:course_detail' id=courses_content.id %}">{{ courses_content.name }}</a></b></h3>
                <h2>Dosen: {{ courses_content.lecturer }}</h2>
                <h2>SKS: {{ courses_content.sks }}</h2>
                <h2><b><a style="color: black" href="{% url 'story5:delete_course' id=courses_content.id %}">Delete courses</a></b></h2>
            </div>

            {% endfor %}
            {% else %}
            <div class="else">
                <h4><b style="color: black">Add your first course!</b></h3>
                <button><a href="{% url 'story5:add_course' %}">Add here!</a></button>
            </div>

            {% endif %}
        </div>
    </div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Livvic:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Livvic:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Satisfy&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rosarivo&family=Solway:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&family=Lobster&display=swap" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block css %}
    {% endblock %}
    <title>{{ title }}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:story3page' %}#home">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:story3page' %}#aboutme">About Me</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:story3page' %}#skills">Skills</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:story3page' %}#experience">Experience</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:story3page' %}#faq">FAQ</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:story3page' %}#contact">Contact</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story3:gallery' %}">Gallery</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'story1:story1page' %}">Story 1</a>
            </li>
          </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>